### ISSUE TITLE
Generate wsdl without explicit file path

### ISSUE THREAD

**Issue by GerryFudd** [nilsmagnus/wsdl2java#83] opened 2019-04-23 21:27 UTC
I am able to use the recommended pattern for wsdlsToGenerate to deploy my project locally, but I would like to do the following:

Generate a .jar file that contains my generated wsdl files and upload that jar file to elasticbeanstalk.

When I use `$projectDir/src/main/resources/wsdl/...wsdl` I still have the absolute file path from the build  directory hardcoded in my jar. This leads to a "file not found" exception when I attempt to run the jar in the elasticbeanstalk instance.

Is there any way to use a classpath or similar strategy to make my jar portable?

**Comment by MaximSokolov** [comment] 2019-04-26 12:27
This is duplicate of #31.
@GerryFudd `-wsdlLocation` parameter worked for me

**Closed** 2019-04-26 12:42 UTC
